stages:
- setup
- build
- build_etc
- test
- unit
- benchmark
- memory
- deploy
- cleanup

before_script:
- module load gcc/7.3.0
- LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)/third-party/lib:$(pwd)/bin/lib

code_quality:
  stage: test
  before_script:
  - shopt -s globstar
  script:
  - cpplint src/**
  allow_failure: true
  dependencies: []

shell_lint:
  stage: test
  script:
  - shellcheck configure.sh
  - shellcheck test/benchmark_all_backends.sh
  - shellcheck test/build_all_backends.sh
  - shellcheck test/build_cov_test_backends.sh
  - shellcheck test/test_all_backends.sh
  - shellcheck test/test_cov_backends.sh
  - shellcheck test/valgrind_all_backends.sh
  allow_failure: true
  dependencies: []

sast:
  stage: test
  script:
  - flawfinder src/
  allow_failure: true
  dependencies: []

check:
  stage: test
  script:
  - cppcheck -j $(nproc) src/
  allow_failure: true
  dependencies: []

config:
  stage: setup
  script:
  - ./configure.sh
  dependencies: []

build_tpp:
  stage: setup
  script:
  - make -j $(nproc) gmp_all
  - make -j $(nproc) ntl_all
  artifacts:
    paths:
    - third-party
    expire_in: 2 hrs
  dependencies: []

build:
  stage: build
  script:
  - make -j $(nproc) all
  artifacts:
    paths:
    - bin
    expire_in: 1 day
  dependencies:
  - build_tpp

build_benchmark:
  stage: build_etc
  script:
  - make -j $(nproc) benchmark
  dependencies:
  - build_tpp
  - build
  artifacts:
    paths:
      - bin/benchmark
    expire_in: 1 day

unit_test:
  stage: unit
  script:
  - ./bin/unittest/tests -t
  dependencies:
  - build_tpp
  - build

cyclo:
  stage: test
  script:
  - lizard -t $(nproc) src/
  allow_failure: true
  dependencies: []

coverage:
  stage: test
  script:
  - make -j $(nproc) all COVERAGE=1
  - make -j $(nproc) testall COVERAGE=1
  - mkdir -p doc/coverage
  - gcovr -j $(nproc) --verbose -r . --filter src/[^/]+/lib/* --filter src/* --html --html-details -o doc/coverage/index.html --print-summary
  allow_failure: true
  dependencies:
  - build_tpp
  artifacts:
    paths:
    - doc/coverage
    expire_in: 3 hours

pages:
  stage: deploy
  script:
  - make -j $(nproc) docs
  - mkdir public
  - mv doc/apidocs/html public
  - mv doc/coverage public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master
  allow_failure: true
  dependencies:
  - coverage

clean:
  stage: cleanup
  script:
  - make -j $(nproc) clobber
  when: always
  dependencies: []

memleak:
  stage: memory
  script:
  - make -j $(nproc) all MEM=1
  - valgrind --leak-check=yes ./bin/unittest/tests
  only:
  - schedules
  tags:
  - linux
  dependencies: []

benchmark_basic:
  stage: benchmark
  script:
  - ./bin/benchmark/basic_test --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv 
  dependencies:
  - build_benchmark
  - build
  - build_tpp
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 month

benchmark_crypto:
  stage: benchmark
  script:
  - ./bin/benchmark/Crypto --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv
  dependencies:
  - build_benchmark
  - build
  - build_tpp
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 month

benchmark_encoding:
  stage: benchmark
  script:
  - ./bin/benchmark/Encoding --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv
  dependencies:
  - build_benchmark
  - build
  - build_tpp
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 month

benchmark_integermath:
  stage: benchmark
  script:
  - ./bin/benchmark/IntegerMath --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv
  dependencies:
  - build_benchmark
  - build
  - build_tpp
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 month

benchmark_lattice:
  stage: benchmark
  script:
  - ./bin/benchmark/Lattice --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv
  dependencies:
  - build_benchmark
  - build
  - build_tpp
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 month

benchmark_nbtheory:
  stage: benchmark
  script:
  - ./bin/benchmark/NbTheory --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv
  dependencies:
  - build_benchmark
  - build
  - build_tpp
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 month

benchmark_she:
  stage: benchmark
  script:
  - ./bin/benchmark/SHE --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv
  dependencies:
  - build_benchmark
  - build
  - build_tpp
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 month

benchmark_vectormath:
  stage: benchmark
  script:
  - ./bin/benchmark/VectorMath --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv
  dependencies:
  - build_benchmark
  - build
  - build_tpp
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 month

benchmark_lib:
  stage: benchmark
  script:
  - ./bin/benchmark/lib-benchmark --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}" --benchmark_out_format=csv
  dependencies:
  - build_benchmark
  - build
  - build_tpp
  artifacts:
    paths:
      - "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 month
