## for mac OSx

BOOSTINCLUDE := -I /boost_1_61_0
OMPINCLUDE := -I /opt/local/include/libomp -fopenmp
#CPPSTD := -std=gnu++0x
CC := clang++ # This is the main compiler
CPPSTD := -std=c++0x

LIBSUFFIX := .dylib
LIBCMD := -fopenmp -dynamiclib -undefined suppress -flat_namespace

RDYNAMIC := 

JNIBUILD :=  
JNILIB := libPalisadeCryptoWrapper.jnilib
JNILINKPARM := -framework JavaVM

