## for mac OSx

OMPINCLUDE := -I /opt/local/include/libomp -fopenmp
CC := clang++
CPPSTD := -std=c++11 -stdlib=libc++

LIBSUFFIX := .dylib
LIBCMD := -dynamiclib -undefined suppress -flat_namespace

RDYNAMIC := 

JNIBUILD :=  
JNILIB := libPalisadeCryptoWrapper.jnilib
JNILINKPARM := -framework JavaVM

PYINCLUDE := $(shell python-config --include)
LIBPYTHON := -lpython2.7 
