#
#Copyright (c) 2016, New Jersey Institute of Technology (NJIT)
#All rights reserved.
#Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
#met:
#1. Redistributions of source code must retain the above copyright
#notice, this list of conditions and the following disclaimer.
#2. Redistributions in binary form must reproduce the above copyright
#notice, this list of conditions and the following disclaimer in the
#documentation and/or other materials provided with the distribution.
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
#IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
#TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
#PARTICULAR PURPOSE ARE DISCLAIMED.
#IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
#ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
#STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
#IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#POSSIBILITY OF SUCH DAMAGE.
#

#this is the actual target that gets called when make is executed (part of all in Makefile)
#it makes the test library, actual palisade tests

################
TESTTARGET := test/bin/tests

.PHONY:alltesttargets
alltesttargets: make_tests docteststrings 
#alltesttargets: make_tests docteststrings $(TESTTARGET)
#alltesttargets: $(TESTTARGET) docteststrings

#.PHONY: make_tests
make_tests:  $(TESTTARGET)
#	@echo '$(TESTTARGET)'




# the following are the directories associated with the test system 
TESTSRCDIR := test/src
TESTBUILDDIR := test/build
TESTTARGETDIR := test/bin
TESTTARGET := test/bin/tests

#DBC: what is the following for?
check: $(TESTTARGET)   
#	$(TESTTARGET)


LIBSOURCES := $(shell find $(SRCDIR) -type f -name *.$(SRCEXT) | xargs grep -L "main()")
LIBOBJECTS := $(patsubst $(SRCDIR)/%,$(BUILDDIR)/%,$(LIBSOURCES:.$(SRCEXT)=.o))



TESTSOURCES := $(shell find $(TESTSRCDIR) -type f -name *.$(SRCEXT))
TESTOBJECTS := $(patsubst $(TESTSRCDIR)/%,$(TESTBUILDDIR)/%,$(TESTSOURCES:.$(SRCEXT)=.o))
TESTLIB := -pthread #-lmongoclient -L lib -lboost_thread-mt -lboost_filesystem-mt -lboost_system-mt

TESTLIBSRCEXT := cc
TESTLIBSRCDIR := test/include/gtest
TESTLIBSOURCES := $(shell find $(TESTLIBSRCDIR) -type f -name *.$(TESTLIBSRCEXT))
TESTLIBOBJECTS := $(patsubst $(TESTLIBSRCDIR)/%,$(TESTBUILDDIR)/%,$(TESTLIBSOURCES:.$(TESTLIBSRCEXT)=.o))

# Points to the root of Google Test, relative to where this file is.
# Remember to tweak this if you move this file.
#GTEST_DIR = test/include

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS =	test/include/gtest/gtest.h
#		$(GTEST_DIR)/include/gtest/gtest-death-test.h \
#		$(GTEST_DIR)/include/gtest/gtest-message.h \
#		$(GTEST_DIR)/include/gtest/gtest-printers.h \
#		$(GTEST_DIR)/include/gtest/gtest-spi.h \
#		$(GTEST_DIR)/include/gtest/gtest-typed-test.h \
#		$(GTEST_DIR)/include/gtest/gtest.h \
#		$(GTEST_DIR)/include/gtest/gtest-param-test.h \
#		$(GTEST_DIR)/include/gtest/gtest_prod.h \
#		$(GTEST_DIR)/include/gtest/gtest-test-part.h \
##GTEST_HEADERS =	$(GTEST_DIR)/include/gtest/*.h \
#               $(GTEST_DIR)/include/gtest/internal/*.h

$(TESTBUILDDIR)/%.o: $(TESTLIBSRCDIR)/%.$(TESTLIBSRCEXT)
	@mkdir -p $(@D)
#	@echo " $(BUILDDIR)"
#	@echo "------ $(CC) $(CPPFLAGS) $(INC) $(TESTLIB) -c -o $@ $<"; $(CC) $(CPPFLAGS) $(INC) $(TESTLIB) -c -o $@ $<
	@echo "$(CC) $(CPPFLAGS) $(INC) $(TESTLIB) -c -o $@ $<"; $(CC) $(CPPFLAGS) $(INC) $(TESTLIB) -c -o $@ $<
	@echo "ar -rv $(TESTBUILDDIR)/libgtest.a $@"; ar -rv $(TESTBUILDDIR)/libgtest.a $@

$(TESTBUILDDIR)/%.o: $(TESTSRCDIR)/%.$(SRCEXT)
	@mkdir -p $(@D)
#	@echo " $(BUILDDIR)"
	@echo " $(CC) $(CPPFLAGS) $(INC) $(TESTLIB) -c -o $@ $<"; $(CC) $(CPPFLAGS) $(INC) $(TESTLIB) -c -o $@ $<

$(TESTTARGET): $(TESTOBJECTS) $(TESTLIBOBJECTS) $(LIBOBJECTS)
	@echo 'linking $(TESTTARGET)'
	@echo "$(TESTLIBSRCEXT)"
	@echo "$(TESTLIBSRCDIR)"
	@echo "$(TESTLIBSOURCES)"
	@echo "$(TESTLIBOBJECTS)"
	@echo " Linking..."
	@mkdir -p $(TESTTARGETDIR)
	@echo " $(CC) $^ $(TESTLIB) $(TESTBUILDDIR)/libgtest.a -o $(TESTTARGET)"; $(CC) $^ $(TESTLIB) $(TESTBUILDDIR)/libgtest.a -o $(TESTTARGET)

.PHONY: runtests
runtests: $(TESTTARGET)
	$(TESTTARGET)


#################

.PHONY: docteststrings
docteststrings:
	@echo 'the following make strings are defined'
	@echo 'TESTTARGET $(TESTTARGET)'
	@echo 'TESTOBJECTS $(TESTOBJECTS)'
	@echo 'TESTSOURCES $(TESTSOURCES)'
	@echo 'TESTLIBOBJECTS $(TESTLIBOBJECTS)'
	@echo 'LIBOBJECTS $(LIBOBJECTS)'
	@echo 'TESTLIBSRCEXT $(TESTLIBSRCEXT)'
	@echo 'TESTLIBSRCDIR $(TESTLIBSRCDIR)'
	@echo 'TESTLIBSOURCES $(TESTLIBSOURCES)'
	@echo 'TESTLIBOBJECTS $(TESTLIBOBJECTS)'
	@echo 'TESTSRCDIR $(TESTSRCDIR)'
	@echo 'TESTBUILDDIR $(TESTBUILDDIR)'
	@echo 'INC $(INC)'
	@echo 'LIB $(LIB)'

#this target is used to cleanup, it is called from the top Makefile
.PHONEY: cleantests
cleantests:
	@echo " Cleaning...";
	@echo " $(RM) -r $(TESTBUILDDIR) $(TESTTARGETDIR)"; $(RM) -r $(TESTBUILDDIR) $(TESTTARGETDIR)

