## for linux

BOOSTINCLUDE := -I /afs/cad/linux/boost-1.60-sl6/include/

OMPINCLUDE := 

CC := g++ # This is the main compiler
CPPSTD := -std=gnu++11


LIBSUFFIX := .so
LIBCMD := -fPIC -shared -Wl,--export-dynamic

RDYNAMIC := -rdynamic

JNIBUILD :=  
JNILIB := libPalisadeCryptoWrapper.so

