## for mingw64 on windows

BOOSTINCLUDE := -I C:/boost_1_60_0
OMPINCLUDE := 
CPPSTD := -std=gnu++11

PALISADELIB := libPALISADE.dll
LIBCMD := -s -shared -Wl,--subsystem,windows 

EXESUFFIX := .exe

MINGWREGEX := -Lc:/Mingw64/mingw64/opt/lib -lregex -lshlwapi

RDYNAMIC := 

JNIBUILD :=  -I "C:/Program Files/java/jdk1.8.0_73/include" -I "C:/Program Files/java/jdk1.8.0_73/include/win32"
JNILIB := PalisadeCryptoWrapper.dll

include Makefile.common

