#
#Copyright (c) 2015, New Jersey Institute of Technology (NJIT)
#All rights reserved.
#Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
#met:
#1. Redistributions of source code must retain the above copyright
#notice, this list of conditions and the following disclaimer.
#2. Redistributions in binary form must reproduce the above copyright
#notice, this list of conditions and the following disclaimer in the
#documentation and/or other materials provided with the distribution.
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
#IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
#TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
#PARTICULAR PURPOSE ARE DISCLAIMED.
#IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
#ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
#STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
#IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#POSSIBILITY OF SUCH DAMAGE.
#

.PHONY:alltargets
alltargets: $(TARGETSMAIN)

$(BUILDDIR)/%.o: $(SRCDIR)/%.$(SRCEXT)
	@mkdir -p $(BUILDDIR)
	@mkdir -p $(BUILDDIR)/crypto
	@mkdir -p $(BUILDDIR)/obfuscate
	@mkdir -p $(BUILDDIR)/encoding
	@mkdir -p $(BUILDDIR)/lattice
	@mkdir -p $(BUILDDIR)/math
	@mkdir -p $(BUILDDIR)/math/cpu8bit
	@mkdir -p $(BUILDDIR)/math/cpu_int
	@mkdir -p $(BUILDDIR)/multilinearmap
	@mkdir -p $(BUILDDIR)/utils
#	@echo " $@"
#	@echo " $<"
#	@echo " $(BUILDDIR)"
#	@echo " $(SRCDIR)"
	@echo " $(CC) $(CPPFLAGS) $(INC) -c -o $@ $< "; $(CC) $(CPPFLAGS) $(INC) -c -o $@ $<

$(BUILDDIRMAIN)/%.o: $(SRCDIR)/%.$(SRCEXT)
	@mkdir -p $(BUILDDIRMAIN)
	@echo " $(CC) $(CPPFLAGS) $(INC) -c -o $@ $< "; $(CC) $(CPPFLAGS) $(INC) -c -o $@ $<

$(TARGETDIR)/%: $(OBJECTSDEEP) $(OBJECTSMAIN)
	@mkdir -p $(TARGETDIR)
#	@echo " $(SOURCESMAIN)"
#	@echo " -- $@"
#	@echo " -- $(@F)"
#	@echo " -- $^"
#	@echo " $(OBJECTSDEEP)"
#	@echo " $(BUILDDIR)/$@.o"
#	@echo " -- $(BUILDDIRMAIN)/$@.o"
#	@echo " $^"
	@echo " $(CC) $(OBJECTSDEEP) $(BUILDDIRMAIN)/$(@F).o -o $@ $(LIB)"; $(CC) $(OBJECTSDEEP) $(BUILDDIRMAIN)/$(@F).o -o $@ $(LIB)

#$(OBJECTSMAIN): 
#	@echo " $@"
#	@echo " $<"
#	@echo " $^"
#	@mkdir -p $(BUILDDIR)
#	@echo " $(CC) $(CPPFLAGS) $(INC) -c -o $(BUILDDIR)/$@.o $(SRCDIR)/$@.$(SRCEXT)"; $(CC) $(CPPFLAGS) $(INC) -c -o $(BUILDDIR)/$@.o $(SRCDIR)/$@.$(SRCEXT)

.PHONEY: cleantargets
cleantargets:
	@echo " Cleaning...";
	@echo " $(RM) -r $(BUILDDIR) $(TARGETDIR)"; $(RM) -r $(BUILDDIR) $(TARGETDIR)

