/*
 * testJson.cpp
 *
 *  Created on: May 22, 2016
 *      Author: gerardryan
 */

#include <iostream>
#include <fstream>

#include "../../lib/encoding/byteplaintextencoding.h"
#include "../../lib/utils/cryptoutility.h"
#include "../../lib/utils/debug.h"

#include <chrono>

#include "../../lib/utils/serializablehelper.h"
#include "../../lib/utils/cryptocontexthelper.h"

using namespace std;
using namespace lbcrypto;

#include "testJson.h"

template<typename Element>
void testJson(
		const std::string cID,
		const BytePlaintextEncoding& newPtxt,
		TestJsonParms<Element> *tp,
		bool skipReEncrypt) {

	shared_ptr<LPPublicKey<Element>>	pkDeserialized;
	shared_ptr<LPPrivateKey<Element>>	skDeserialized;
	shared_ptr<LPEvalKey<Element>>		evalKeyDeserialized;
	shared_ptr<LPPrivateKey<Element>>	newSKDeserialized;

	cout << "----------------------START JSON FACILITY TESTING-------------------------" << endl;

	size_t chunksize = newPtxt.GetChunksize(tp->ctx.GetCryptoParameters()->GetElementParams()->GetCyclotomicOrder(), tp->ctx.GetCryptoParameters()->GetPlaintextModulus());
	if( newPtxt.size() > chunksize ) {
		cout << "This test code won't work when the plaintext size (" << newPtxt.size()
				<< ") is bigger than the chunksize (" << chunksize << ")" << endl;
		return;
	}

	string jsonFileName;
	string jsonRep;

	cout << "---BEGIN LPPublicKey" + cID + " SERIALIZATION---" << endl;
	Serialized testMap1;
	if (tp->pk->Serialize(&testMap1, "Enc")) {
		jsonFileName = "LPPublicKey" + cID + "_Enc.txt";
		cout << "Saving to " << jsonFileName;
		if (SerializableHelper::WriteSerializationToFile(testMap1, jsonFileName))
			cout << " ... success!" << endl;
		else {
			cout << " ... failed!" << endl;
			return;
		}
	} else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END LPPublicKey" + cID + " SERIALIZATION TESTING---" << endl << endl;

	cout << "---BEGIN LPPrivateKey" + cID + " SERIALIZATION---" << endl;
	Serialized testMap2;
	if (tp->sk->Serialize(&testMap2, "Enc")) {
		jsonFileName = "LPPrivateKey" + cID + "_Enc.txt";
		cout << "Serialization saved to " << jsonFileName;
		if (SerializableHelper::WriteSerializationToFile(testMap2, jsonFileName))
			cout << " ... success!" << endl;
		else {
			cout << " ... failed!" << endl;
			return;
		}
	} else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END LPPrivateKey" + cID + " SERIALIZATION---" << endl << endl;

	cout << "---BEGIN LPPublicKey" + cID + " DESERIALIZATION---" << endl;
	jsonFileName = "LPPublicKey" + cID + "_Enc.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, &testMap1);

	if ( pkDeserialized = tp->ctx.deserializePublicKey(testMap1) ) {
		cout << "Deserialized into pkDeserialized" << endl;
	} else {
		cout << "FAILED" << endl;
		return;
	}

	cout << "---END LPPublicKey" + cID + " DESERIALIZATION---" << endl << endl;

	cout << "---BEGIN LPPrivateKey" + cID + " DESERIALIZATION---" << endl;
	jsonFileName = "LPPrivateKey" + cID + "_Enc.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, &testMap2);
	if (skDeserialized = tp->ctx.deserializeSecretKey(testMap2) ) {
		cout << "Deserialized into skDeserialized" << endl;
	} else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END LPPrivateKey" + cID + " DESERIALIZATION---" << endl << endl;

	cout << "----------BEGIN LPAlgorithm" + cID + ".Encrypt TESTING----------" << endl;
	cout << "Calling Encrypt in LPAlgorithm" + cID + " with deserialized instance of LPPublicKey" + cID + "" << endl;
	vector<shared_ptr<Ciphertext<ILVector2n>>> testCiphertext;
	testCiphertext = tp->ctx.Encrypt(pkDeserialized, newPtxt);
	if( testCiphertext.size() == 0 ) {
		cout << "FAILED" << endl;
		return;
	}
	cout << "----------END LPAlgorithmPRE" + cID + ".Encrypt TESTING----------" << endl << endl;

	cout << "---BEGIN CIPHERTEXT SERIALIZATION---" << endl;
	cout << "Serializing testCiphertext object generated by Encrypt TESTING..." << endl;
	Serialized testMap3;
	if (testCiphertext[0]->Serialize(&testMap3, "Enc")) {
		jsonFileName = "Ciphertext" + cID + "_Enc.txt";
		cout << "Serialization saved to " << jsonFileName;
		if (SerializableHelper::WriteSerializationToFile(testMap3, jsonFileName))
			cout << " ... success!" << endl;
		else {
			cout << " ... failed!" << endl;
			return;
		}
	} else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END CIPHERTEXT SERIALIZATION---" << endl << endl;

	cout << "---BEGIN CIPHERTEXT DESERIALIZATION---" << endl;
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, &testMap3);
	shared_ptr<Ciphertext<Element>> ciphertextDeserialized;
	if (ciphertextDeserialized = tp->ctx.deserializeCiphertext(testMap3) )
		cout << "Deserialized into ciphertextDeserialized" << endl;
	else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END CIPHERTEXT DESERIALIZATION---" << endl << endl;

	cout << "----------BEGIN LPAlgorithm" + cID + ".Decrypt TESTING----------" << endl;
	cout << "Calling Decrypt in LPAlgorithm" + cID + " with deserialized instances of" << endl;
	cout << "LPPrivateKey" + cID + " and Ciphertext." << endl;
	BytePlaintextEncoding testPlaintextRec;
	vector<shared_ptr<Ciphertext<Element>>> ctDeser;
	ctDeser.push_back(ciphertextDeserialized);
	DecryptResult testResult = tp->ctx.Decrypt(skDeserialized, ctDeser, &testPlaintextRec);
	if( testResult.isValid == false ) {
		cout << "FAILED" << endl;
		return;
	}
	ctDeser.clear();

	cout << "Recovered plaintext from call to Decrypt: " << endl;
	cout << testPlaintextRec << endl;
	cout << "----------END LPAlgorithm" + cID + ".Decrypt TESTING----------" << endl << endl;

	if( skipReEncrypt )
		return;

	cout << "---BEGIN LPEvalKey" + cID + " SERIALIZATION---" << endl;
	Serialized testMap4;
	if (tp->evalKey->Serialize(&testMap4, "Pre")) {
		jsonFileName = "LPEvalKey" + cID + "_Pre.txt";
		cout << "Saving serialization to " << jsonFileName;
		if (SerializableHelper::WriteSerializationToFile(testMap4, jsonFileName))
			cout << " ... success!" << endl;
		else {
			cout << " ... failed!" << endl;
			return;
		}
	} else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END LPEvalKey" + cID + " SERIALIZATION TESTING---" << endl << endl;

	cout << "---BEGIN LPEvalKey" + cID + " DESERIALIZATION---" << endl;
	jsonFileName = "LPEvalKey" + cID + "_Pre.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, &testMap4);
	if( evalKeyDeserialized = tp->ctx.deserializeEvalKey(testMap4) )
		cout << "Deserialized into evalKeyDeserialized" << endl;
	else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END LPEvalKey" + cID + " DESERIALIZATION---" << endl << endl;

	cout << "----------BEGIN LPAlgorithmPRE" + cID + ".ReEncrypt TESTING----------" << endl;
	cout << "Calling ReEncrypt in LPAlgorithmPRE" + cID + " with deserialized instances of" << endl;
	cout << "LPEvalKey" + cID + " and Ciphertext." << endl;

	vector<shared_ptr<Ciphertext<Element>>> ct;
	vector<shared_ptr<Ciphertext<Element>>> ctRe;
	ct.push_back(ciphertextDeserialized);

	shared_ptr<Ciphertext<Element>> preCiphertext;
	ctRe = tp->ctx.ReEncrypt(evalKeyDeserialized, ct);
	preCiphertext = ctRe[0];
	cout << "----------END LPAlgorithmPRE" + cID + ".ReEncrypt TESTING----------" << endl << endl;

	cout << "---BEGIN PRE LPPrivateKey" + cID + " SERIALIZATION---" << endl;
	cout << "Serializing previously used newSK object..." << endl;
	Serialized testMap5;
	if (tp->newSK->Serialize(&testMap5, "Pre")) {
		jsonFileName = "LPPrivateKey" + cID + "_Pre.txt";
		cout << "Saving serialization to " << jsonFileName << endl;
		if (SerializableHelper::WriteSerializationToFile(testMap5, jsonFileName))
			cout << " ... success!" << endl;
		else {
			cout << " ... failed!" << endl;
			return;
		}
	} else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END PRE LPPrivateKey" + cID + " SERIALIZATION---" << endl << endl;

	cout << "---BEGIN PRE CIPHERTEXT SERIALIZATION---" << endl;
	cout << "Serializing preCiphertext object generated by ReEncrypt TESTING..." << endl;
	Serialized testMap6;
	if (preCiphertext->Serialize(&testMap6, "Pre")) {
		jsonFileName = "Ciphertext" + cID + "_Pre.txt";
		cout << "Saving serialization to " << jsonFileName << endl;
		if (SerializableHelper::WriteSerializationToFile(testMap6, jsonFileName))
			cout << " ... success!" << endl;
		else {
			cout << " ... failed!" << endl;
			return;
		}
	} else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END PRE CIPHERTEXT SERIALIZATION---" << endl << endl;

	cout << "---BEGIN PRE LPPrivateKey" + cID + " DESERIALIZATION---" << endl;
	jsonFileName = "LPPrivateKey" + cID + "_Pre.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, &testMap5);
	if( newSKDeserialized = tp->ctx.deserializeSecretKey(testMap5) )
		cout << "Deserialized into newSKDeserialized" << endl;
	else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END PRE LPPrivateKey" + cID + " DESERIALIZATION---" << endl << endl;

	cout << "---BEGIN PRE CIPHERTEXT DESERIALIZATION---" << endl;
	jsonFileName = "Ciphertext" + cID + "_Pre.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, &testMap3);
	shared_ptr<Ciphertext<Element>> preCiphertextDeserialized;
	if( preCiphertextDeserialized = tp->ctx.deserializeCiphertext(testMap3) )
		cout << "Deserialized into preCiphertextDeserialized" << endl;
	else {
		cout << "FAILED" << endl;
		return;
	}
	cout << "---END PRE CIPHERTEXT DESERIALIZATION---" << endl << endl;

	cout << "----------BEGIN LPAlgorithmPRE" + cID + ".Decrypt TESTING----------" << endl;
	cout << "Calling Decrypt in LPAlgorithmPRE" + cID + " with deserialized instances of" << endl;
	cout << "PRE LPPrivateKey" + cID + " and PRE Ciphertext." << endl;
	BytePlaintextEncoding testPlaintextPreRec;
	vector<shared_ptr<Ciphertext<Element>>> preCtVec;
	preCtVec.push_back(preCiphertextDeserialized);
	DecryptResult testResult1 = tp->ctx.Decrypt(newSKDeserialized, preCtVec, &testPlaintextPreRec);
	preCtVec.clear();

	cout << "Recovered plaintext from call to PRE Decrypt: " << endl;
	cout << testPlaintextPreRec << endl;
	cout << "----------END LPAlgorithmPRE" + cID + ".Decrypt TESTING----------" << endl << endl;
	std::cout
			<< "----------------------END JSON FACILITY TESTING-------------------------"
			<< endl << endl;
}


