/*
 * testJson.cpp
 *
 *  Created on: May 22, 2016
 *      Author: gerardryan
 */

#include <iostream>
#include <fstream>
#include "../../lib/math/backend.h"
//#include "../../lib/math/cpu8bit/backend.h"
#include "../../lib/utils/inttypes.h"
#include "../../lib/math/nbtheory.h"
//#include <thread>
#include "../../lib/lattice/elemparams.h"
#include "../../lib/lattice/ilparams.h"
#include "../../lib/lattice/ildcrtparams.h"
#include "../../lib/lattice/ilelement.h"
//#include "../../lib/il2n.h"
#include "../../lib/math/distrgen.h"
#include "../../lib/crypto/lwecrypt.h"
#include "../../lib/crypto/lwecrypt.cpp"
#include "../../lib/crypto/lweautomorph.cpp"
#include "../../lib/crypto/lwepre.h"
#include "../../lib/crypto/lwepre.cpp"
#include "../../lib/crypto/lweahe.cpp"
#include "../../lib/crypto/lweshe.cpp"
#include "../../lib/crypto/lwefhe.cpp"
#include "../../lib/lattice/ilvector2n.h"
#include "../../lib/lattice/ilvectorarray2n.h"
//#include "../../lib/time.h"

#include "../../lib/utils/debug.h"
#include "../../lib/crypto/ciphertext.cpp"
//#include "../../lib/vld.h"
#include <chrono>
//#include "../../lib/gtest/gtest.h"
//#include "../../lib/math/cpu8bit/binint.h"
//#include "../../lib/math/cpu8bit/binvect.h"
//#include "../../lib/math/cpu8bit/binmat.h"

#include "../../lib/utils/serializablehelper.h"

using namespace std;
using namespace lbcrypto;


void testJson(const LPPublicKeyLTV<ILVector2n>& pk,
		const LPPrivateKeyLTV<ILVector2n>& sk,
		const LPPublicKeyEncryptionSchemeLTV<ILVector2n>& algorithm,
		const ByteArrayPlaintextEncoding& newPtxt,
		const LPEvalKeyLTV<ILVector2n>& evalKey,
		const LPPrivateKeyLTV<ILVector2n>& newSK) {
	string jsonFileName = "";
	cout << "---BEGIN LPPublicKeyLTV SERIALIZATION---" << endl;
	cout << "Serializing previously used pk object..." << endl;
	Serialized testMap1;
	if (pk.Serialize(testMap1, "Enc")) {
		jsonFileName = "LPPublicKeyLTV_Enc.txt";
		cout << "Saving to " << jsonFileName;
		if (SerializableHelper::WriteSerializationToFile(testMap1,
				jsonFileName))
			cout << " ... success!";

		cout << endl;
	}
	cout << "---END LPPublicKeyLTV SERIALIZATION TESTING---" << endl;
	cout << "---BEGIN LPPrivateKeyLTV SERIALIZATION---" << endl;
	cout << "Serializing previously used sk object..." << endl;
	Serialized testMap2;
	if (sk.Serialize(testMap2, "Enc")) {
		jsonFileName = "LPPrivateKeyLTV_Enc.txt";
		cout << "Serialization saved to " << jsonFileName;
		if (SerializableHelper::WriteSerializationToFile(testMap2,
				jsonFileName))
			cout << " ... success!";

		cout << endl;
	}
	cout << "---END LPPrivateKeyLTV SERIALIZATION---" << endl;
	cout << "---BEGIN LPPublicKeyLTV DESERIALIZATION---" << endl;
	jsonFileName = "LPPublicKeyLTV_Enc.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, testMap1);
	LPPublicKeyLTV<ILVector2n> pkDeserialized;
	LPCryptoParametersLTV<ILVector2n> json_cryptoParamsPub;
	pkDeserialized.SetCryptoParameters(&json_cryptoParamsPub);
	if (pkDeserialized.Deserialize(testMap1))
		cout << "Deserialized into pkDeserialized" << endl;

	cout << "---END LPPublicKeyLTV DESERIALIZATION---" << endl;
	cout << "---BEGIN LPPrivateKeyLTV DESERIALIZATION---" << endl;
	jsonFileName = "LPPrivateKeyLTV_Enc.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, testMap2);
	LPPrivateKeyLTV<ILVector2n> skDeserialized;
	LPCryptoParametersLTV<ILVector2n> json_cryptoParamsPriv;
	skDeserialized.SetCryptoParameters(&json_cryptoParamsPriv);
	if (skDeserialized.Deserialize(testMap2))
		cout << "Deserialized into skDeserialized" << endl;

	cout << "---END LPPrivateKeyLTV DESERIALIZATION---" << endl;
	cout << "\n" << endl;
	cout << "----------BEGIN LPAlgorithmLTV.Ecrypt TESTING----------" << endl;
	cout << "Calling Encrypt in LPAlgorithmLTV with deserialized instance of"
			<< endl;
	cout << "LPPublicKeyLTV." << endl;
	Ciphertext<ILVector2n> testCiphertext;
	algorithm.Encrypt(pkDeserialized, newPtxt, &testCiphertext);
	cout << "----------END LPAlgorithmPRELTV.ReEcrypt TESTING----------"
			<< endl;
	cout << "\n" << endl;
	cout << "---BEGIN CIPHERTEXT SERIALIZATION---" << endl;
	cout << "Serializing testCiphertext object generated by Encrypt TESTING..."
			<< endl;
	Serialized testMap3;
	if (testCiphertext.Serialize(testMap3, "Enc")) {
		jsonFileName = "Ciphertext_Enc.txt";
		cout << "Serialization saved to " << jsonFileName;
		if (SerializableHelper::WriteSerializationToFile(testMap3,
				jsonFileName))
			cout << " ... success!";

		cout << endl;
	}
	cout << "---END CIPHERTEXT SERIALIZATION---" << endl;
	cout << "---BEGIN CIPHERTEXT DESERIALIZATION---" << endl;
	jsonFileName = "Ciphertext_Enc.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, testMap3);
	Ciphertext<ILVector2n> ciphertextDeserialized;
	if (ciphertextDeserialized.Deserialize(testMap3))
		cout << "Deserialized into ciphertextDeserialized" << endl;

	cout << "---END CIPHERTEXT DESERIALIZATION---" << endl;
	cout << "\n" << endl;
	cout << "----------BEGIN LPAlgorithmLTV.Decrypt TESTING----------" << endl;
	cout << "Calling Decrypt in LPAlgorithmLTV with deserialized instances of"
			<< endl;
	cout << "LPPrivateKeyLTV and Ciphertext." << endl;
	ByteArrayPlaintextEncoding testPlaintextRec;
	DecodingResult testResult = algorithm.Decrypt(skDeserialized,
			ciphertextDeserialized, &testPlaintextRec);
	testPlaintextRec.Unpad<ZeroPad>();
	cout << "Recovered plaintext from call to Decrypt: " << endl;
	cout << testPlaintextRec << endl;
	cout << "----------END LPAlgorithmLTV.Decrypt TESTING----------" << endl;
	cout << "\n" << endl;
	cout << "---BEGIN LPEvalKeyLTV SERIALIZATION---" << endl;
	cout << "Serializing previously used evalKey object..." << endl;
	Serialized testMap4;
	if (evalKey.Serialize(testMap4, "Pre")) {
		jsonFileName = "LPEvalKeyLTV_Pre.txt";
		if (SerializableHelper::WriteSerializationToFile(testMap4,
				jsonFileName))
			cout << "Serialization saved to " << jsonFileName << endl;
	}
	cout << "---END LPEvalKeyLTV SERIALIZATION TESTING---" << endl;
	cout << "---BEGIN LPEvalKeyLTV DESERIALIZATION---" << endl;
	jsonFileName = "LPEvalKeyLTV_Pre.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, testMap4);
	LPEvalKeyLTV<ILVector2n> evalKeyDeserialized;
	LPCryptoParametersLTV<ILVector2n> json_cryptoParamsEval;
	evalKeyDeserialized.SetCryptoParameters(&json_cryptoParamsEval);
	evalKeyDeserialized.Deserialize(testMap4);
	cout << "Deserialized into evalKeyDeserialized" << endl;
	cout << "---END LPEvalKeyLTV DESERIALIZATION---" << endl;
	cout << "\n" << endl;
	cout << "----------BEGIN LPAlgorithmPRELTV.ReEcrypt TESTING----------"
			<< endl;
	cout
			<< "Calling ReEncrypt in LPAlgorithmPRELTV with deserialized instances of"
			<< endl;
	cout << "LPEvalKeyLTV and Ciphertext." << endl;
	Ciphertext<ILVector2n> preCiphertext;
	algorithm.ReEncrypt(evalKeyDeserialized, ciphertextDeserialized,
			&preCiphertext);
	cout << "----------END LPAlgorithmPRELTV.ReEcrypt TESTING----------"
			<< endl;
	cout << "\n" << endl;
	cout << "---BEGIN PRE LPPrivateKeyLTV SERIALIZATION---" << endl;
	cout << "Serializing previously used newSK object..." << endl;
	Serialized testMap5;
	if (newSK.Serialize(testMap5, "Pre")) {
		jsonFileName = "LPPrivateKeyLTV_Pre.txt";
		if (SerializableHelper::WriteSerializationToFile(testMap5,
				jsonFileName))
			cout << "Serialization saved to " << jsonFileName << endl;
	}
	cout << "---END PRE LPPrivateKeyLTV SERIALIZATION---" << endl;
	cout << "---BEGIN PRE CIPHERTEXT SERIALIZATION---" << endl;
	cout << "Serializing preCiphertext object generated by ReEncrypt TESTING..."
			<< endl;
	Serialized testMap6;
	if (preCiphertext.Serialize(testMap6, "Pre")) {
		jsonFileName = "Ciphertext_Pre.txt";
		if (SerializableHelper::WriteSerializationToFile(testMap6,
				jsonFileName))
			cout << "Serialization saved to " << jsonFileName << endl;
	}
	cout << "---END PRE CIPHERTEXT SERIALIZATION---" << endl;
	cout << "---BEGIN PRE LPPrivateKeyLTV DESERIALIZATION---" << endl;
	jsonFileName = "LPPrivateKeyLTV_Pre.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, testMap5);
	LPPrivateKeyLTV<ILVector2n> newSKDeserialized;
	LPCryptoParametersLTV<ILVector2n> json_cryptoParamsNewPriv;
	newSKDeserialized.SetCryptoParameters(&json_cryptoParamsNewPriv);
	newSKDeserialized.Deserialize(testMap5);
	cout << "Deserialized into newSKDeserialized" << endl;
	cout << "---END PRE LPPrivateKeyLTV DESERIALIZATION---" << endl;
	cout << "---BEGIN PRE CIPHERTEXT DESERIALIZATION---" << endl;
	jsonFileName = "Ciphertext_Pre.txt";
	cout << "Deserializing instance from " << jsonFileName << endl;
	SerializableHelper::ReadSerializationFromFile(jsonFileName, testMap3);
	Ciphertext<ILVector2n> preCiphertextDeserialized;
	preCiphertextDeserialized.Deserialize(testMap3);
	cout << "Deserialized into preCiphertextDeserialized" << endl;
	cout << "---END PRE CIPHERTEXT DESERIALIZATION---" << endl;
	cout << "\n" << endl;
	cout << "----------BEGIN LPAlgorithmPRELTV.Decrypt TESTING----------"
			<< endl;
	cout
			<< "Calling Decrypt in LPAlgorithmPRELTV with deserialized instances of"
			<< endl;
	cout << "PRE LPPrivateKeyLTV and PRE Ciphertext." << endl;
	ByteArrayPlaintextEncoding testPlaintextPreRec;
	DecodingResult testResult1 = algorithm.Decrypt(newSKDeserialized,
			preCiphertextDeserialized, &testPlaintextPreRec);
	testPlaintextPreRec.Unpad<ZeroPad>();
	cout << "Recovered plaintext from call to PRE Decrypt: " << endl;
	cout << testPlaintextPreRec << endl;
	cout << "----------END LPAlgorithmPRELTV.Decrypt TESTING----------" << endl;
	cout << "\n" << endl;
	std::cout
			<< "----------------------END JSON FACILITY TESTING-------------------------"
			<< endl;
	cout << "\n" << endl;
}


